services:
  frontend:
    container_name: kf2-stats-frontend
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PUBLIC_BACKEND_URL=http://backend:3000/api
    ports:
      - '5000:5000/tcp'
    networks:
      - frontend
networks:
  frontend:
    name: frontend
    external: true