services:
  frontend:
    container_name: kf2-stats-frontend
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    expose:
      - '5000'
    networks:
      - frontend

  nginx-proxy:
    restart: always
    image: nginx
    env_file:
      - .env.production
    ports:
      - '80:80'
    volumes:
      - ./deploy/nginx.template:/etc/nginx/conf.d/nginx.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true
